version: "3"

services:
  server:
    image: nginx:1.25
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${NGINX_PORT}:80
    volumes:
      - ./app:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      app:
        condition: service_started

  app:
    build:
      context: ./
      dockerfile: ./php/Dockerfile
      args:
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
      target: development
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${PHP_PORT}:9000
    volumes:
      - dep_vol:/var/www/html/vendor
      - ./app:/var/www/html
      - ./php/ini/${PHP_INI_FILE}:/usr/local/etc/php/php.ini
      - ./php/ini/conf.d:/usr/local/etc/php/conf.d/
    env_file:
      - ./.env
    environment:
      DB_HOST: db
    command: ["php-fpm"]
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${POSTGRES_PORT}:5432
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3

  cache:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${REDIS_PORT}:6379
    volumes:
      - cache_vol:/data
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  dep_vol:
    driver: local
    driver_opts:
      type: none
      device: ./app/vendor
      o: bind
  db_vol:
  cache_vol:
