version: "3"

services:
  nginx:
    image: nginx:1.25
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${NGINX_PORT}:80
    volumes:
      - ./app:/var/www/
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      php81fpm:
        condition: service_started

  php81fpm:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${PHP_PORT}:9000
    volumes:
      - ./app:/var/www/
      - ./php/ini/${PHP_INI_FILE}:/usr/local/etc/php/php.ini
      - ./php/ini/conf.d:/usr/local/etc/php/conf.d/
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE}
      PGSQL_HOST: postgres
      PGSQL_PORT: 5432
      DB_CONNECTION: pgsql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${POSTGRES_PORT}:5432
    volumes:
      - psql_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${REDIS_PORT}:6379
    volumes:
      - redis_vol:/data
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  psql_vol:
  redis_vol:
