version: "3"

services:
  server:
    image: nginx:${NGINX_VERSION}
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${NGINX_PORT}:80
    volumes:
      - ./app/:/var/www/html/
      - ./nginx/templates/:/etc/nginx/templates/
      - ./nginx/logs/:/var/log/nginx/
    environment:
      APP_NAME: ${APP_NAME}
    depends_on:
      app:
        condition: service_started

  app:
    build:
      context: ./
      dockerfile: ./php/Dockerfile
      target: ${APP_TARGET}
      args:
        PHP_VERSION: ${PHP_VERSION}
    command: ["php-fpm"]
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${PHP_PORT}:9000
    volumes:
      - ./app/:/var/www/html/
    env_file:
      - ./.env
    environment:
      DB_HOST: db
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      composer:
        condition: service_completed_successfully

  composer:
    build:
      context: ./php/composer
      dockerfile: Dockerfile
      args:
        COMPOSER_VERSION: ${COMPOSER_VERSION}
      target: ${APP_TARGET}
    volumes:
      - ./app/:/app

  db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${POSTGRES_PORT}:5432
    volumes:
      - db_vol:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 3

  cache:
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${REDIS_PORT}:6379
    volumes:
      - cache_vol:/data/
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  db_vol:
  cache_vol:
