name: ${APP_NAME}

services:
  server:
    container_name: ${APP_NAME}-server
    image: nginx:${NGINX_VERSION}
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${NGINX_PORT}:80
    volumes:
      - ${APP_CODE_PATH}:/var/www/html/
      - ./nginx/templates/:/etc/nginx/templates/
      - ./nginx/logs/:/var/log/nginx/
    environment:
      APP_NAME: ${APP_NAME}
    depends_on:
      app:
        condition: service_started

  app:
    container_name: ${APP_NAME}-app
    build:
      context: ./
      dockerfile: ./php/Dockerfile
      target: ${APP_TARGET}-app
      args:
        PHP_VERSION: ${PHP_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        user: ${USER}
        uid: ${UID}
    command: php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8080
    restart: unless-stopped
    networks:
      - default
      - rabbitmq
    ports:
      - ${NETWORK_INTERFACE}:${ROAD_RUNNER_PORT}:8080
    volumes:
      - ${APP_CODE_PATH}:/var/www/html/
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE}
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: ${APP_NAME}-rabbitmq
#    ports:
#      - ${NETWORK_INTERFACE}:5672:5672
#      - ${NETWORK_INTERFACE}:15672:15672
#    labels:
#      NAME: rabbitmq
#    volumes:
#      - ./rabbitmq/data/:/var/lib/rabbitmq/
#      - ./rabbitmq/log/:/var/log/rabbitmq/

  adminer:
    container_name: ${APP_NAME}-adminer
    image: adminer:${ADMINER_VERSION}
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${ADMINER_PORT}:8080
    depends_on:
      db:
        condition: service_healthy

#  buggregator:
#    container_name: ${APP_NAME}-buggregator
#    image: ghcr.io/buggregator/server:dev
#    restart: unless-stopped
#    ports:
#      - ${NETWORK_INTERFACE}:8000:8000
#      - ${NETWORK_INTERFACE}:1025:1025
#      - ${NETWORK_INTERFACE}:9912:9912
#      - ${NETWORK_INTERFACE}:9913:9913
#    depends_on:
#      app:
#        condition: service_started

  db:
    container_name: ${APP_NAME}-db
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${POSTGRES_PORT}:5432
    volumes:
      - db-vol:/var/lib/postgresql/data/
      - ./postgres/dump:/dump
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_DATABASE}']
      interval: 5s
      timeout: 5s
      retries: 3

  cache:
    container_name: ${APP_NAME}-cache
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    ports:
      - ${NETWORK_INTERFACE}:${REDIS_PORT}:6379
    volumes:
      - cache-vol:/data/
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  db-vol:
    name: ${APP_NAME}-db-vol
  cache-vol:
    name: ${APP_NAME}-cache-vol

networks:
  default:
    name: ${APP_NAME}-network;
  rabbitmq:
    external: true
