version: "3"

services:
  nginx:
    image: nginx:1.25
    ports:
      - ${NETWORK_INTERFACE}:${NGINX_PORT}:80
    volumes:
      - ./app:/var/www/
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      - php81fpm
      - postgres

  php81fpm:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    ports:
      - ${NETWORK_INTERFACE}:${PHP_PORT}:9000
    volumes:
      - ./app:/var/www/
      - ./php/ini/${PHP_INI_FILE}:/usr/local/etc/php/php.ini
      - ./php/ini/conf.d:/usr/local/etc/php/conf.d/
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE}
    extra_hosts:
      - host.docker.internal:host-gateway

  postgres:
    image: postgres:16
    ports:
      - ${NETWORK_INTERFACE}:${POSTGRES_PORT}:5432
    volumes:
      - psql_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:7.2
    ports:
      - ${NETWORK_INTERFACE}:${REDIS_PORT}:6379

volumes:
  psql_vol:
  redis_vol:
